name: CI

on:
  push:
    branches:
      - main

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: run Lighthouse CI
        run: |
          npm run test:lh:ci
